apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-deploy-patch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"

spec:
  project: default

  source:
    repoURL: https://github.com/learnandgrow459-ui/istio_bookinfo_sample_app.git
    targetRevision: master
    path: argocd-automation/pod_reloader_annotation

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true