apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gw-crds-deploy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  source:
    repoURL: https://github.com/learnandgrow459-ui/istio_bookinfo_sample_app.git
    targetRevision: master
    path: gateway_api/gatewayapi_crds

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
   