apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-deploy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/learnandgrow459-ui/istio_bookinfo_sample_app.git
    targetRevision: master
    path: istio/istio_base

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true